### PR TITLE
Add retrospective template.

### PR DESCRIPTION
**Pull request by karantan**

### CODE REVIEW

**Comment by dmurko** [comment]
I would really try to avoid adding more stuff to work process doc. Maybe create a folder and start putting templates and checklists in there?

**Comment by zupo** [comment]
I'm +1 for having folder for templates.

Also, here (https://github.com/RichardLitt/knowledge/issues/9#issuecomment-343927530) they say GitHub will soon support multiple issue templates. Hope it really does happen!

**Comment by karantan** [comment]
@dmurko & @zupo is this better?

**Comment by dmurko** [comment]
Yes, it'll be more organized. In the next Story we can move other checklists here too (onboarding, etc.).

**Pull request merged**
