### PR TITLE
Add dev link to Three Laws of TDD coding example

### PR DESCRIPTION
**Pull request by cas--**
There is a mention of Three Laws of TDD  in UncleBob Expecting Professionalism and this is a video of it action to aid understanding the process.

### CODE REVIEW

**Comment by zupo** [comment]
I'm slightly -1 on this. I don't want the onboarding list to grow too long. If we add this one in, is there one that we can remove?

**Comment by cas--** [comment]
TDD is one of the suggested Expert Python chapters to read earlier. If we are to suggest TDD then it needs to be clear what is required. Whether it is enforced or not is another matter...

I am painfully aware it is not Python code but the theory still applies directly to Unit Testing such that the code could easily be ported. The reason I chose it was because it follows on from the UncleBob Expecting Professionalism in which he talks about TDD and he explains the TDD process very well. 

@zupo I would suggest dropping the Expert Python chapter 11 on TDD. I also think the Pyramid Quick Tour can be removed as the Quick Tutorial covers it in more detail so it's doubling up on reading.

**Comment by cas--** [comment]
So I found an excellent tutorial that covers both TDD and PDB: https://code.tutsplus.com/tutorials/beginning-test-driven-development-in-python--net-30137

I do feel strongly about keeping the UncleBob TDD video as a follow-on resource so instead I put it onto the same line.

**Comment by cas--** [comment]
Hmm I should have been done those extra changes in a new branch based on this one, sorry guys!

**Comment by zupo** [comment]
I like the proposed changes, well structured, plus at least something was removed to keep onboarding from growing too big. 

+1 for merging, but I want @karantan's opinion as well.

**Pull request merged**
