### PR TITLE
Quit Slack when working!

### PR DESCRIPTION
**Pull request by dmurko**
Read: https://m.signalvnoise.com/is-group-chat-making-you-sweat-744659addf7d
We need to encourage all team members to quit Slack when working. I've been doing this the last few weeks and it's had an enormous beneficial impact on my productivity.

### CODE REVIEW

**Comment by zupo** [comment]
+1000

**Comment by cas--** [comment]
This looks good.

I would like to expand this into a work etiquette surrounding sending and receiving notifications but that is a bigger story.

**Comment by cas--** [comment]
In the sprint retrospective, there seems to be a bit of confusion or further discussion wanted about this addition. I think this PR should be closed and a story created for a bigger discussion about reducing notification load but also how we show we are available, busy and how to notify people, dependent on priority.

**Comment by karantan** [comment]
One thing we might want to do when quitting slack for "do not disturb" mode is to write on #out-of-office chan something like `quitting slack. going silent mode. ping me if you need me.`

**Comment by dmurko** [comment]
This is good for now.

**Pull request closed without merging**
