### PR TITLE
Update instructions for setting up NordVPN Teams

### PR DESCRIPTION
**Pull request by myrheimb**
Update the instructions for NordVPN Teams.
Unfortunately, there doesn't appear to be any way to install/use it on Linux anymore.

### CODE REVIEW

**Review by dmurko — APPROVED** [review]

**Comment by dmurko** [comment]
@am-on @dz0ny Does NordVPN Teams work for you with the Linux client?

**Comment by zupo** [comment]
> Unfortunately, there doesn't appear to be any way to install/use it on Linux anymore.

Uh, what? Then we need to find a new provider.

**Comment by am-on** [comment]
NordVPN Teams doesn't have linux client.

Is this still working https://github.com/niteoweb/operations/pull/1212#issuecomment-573421725?

I never bothered to properly configure it since I rarely need it. I use it through virtual machine.

**Comment by dz0ny** [comment]
@myrheimb Add this

1. Go to https://cp.nordvpnteams.com/downloads 
2. Under Manual configuration download for the user who needs UDP or TCP config for OpenVPN
3. Import to Network Manager under Settings or consult your distribution manual

**Comment by zupo** [comment]
@myrheimb: IIRC you have to be admin i.e. They promised they will allow non-admins to do this at some point.

**Comment by myrheimb** [comment]
Got it - updating the docs now to ask a partner for the files.

**Review by dz0ny — APPROVED** [review]

**Pull request merged**
