### PR TITLE
Moving full table of contents to homepage

### PR DESCRIPTION
**Pull request by dmurko**
Instead of subpages with tables of contents (like operations.md), this puts it all on the homepage.

Yes/no?

### CODE REVIEW

**Comment by dmurko** [comment]
I think it's better this way because it's easier to see what is where and you don't need to click through folders to find that one file.

**Comment by marbeann** [comment]
+1 I like it. But why is Projects first? Wouldn't it be more logical to put Operations first? That is what visitors would be most interested to know - how the company functions.

**Comment by dmurko** [comment]
Because it's primarily for us and I thought projects are the first thing. That said, once you know them and the repos, it's not much more. So maybe I should move it to the bottom.

**Comment by zupo** [comment]
@dmurko there are broken links in `catchup-meetings.md`: https://travis-ci.com/niteoweb/handbook/builds/83655688#L888

**Pull request merged**
