### PR TITLE
Cleanup capilization in work-process pages

### PR DESCRIPTION
**Pull request by cas--**
A style based on wikipedia style guide is now being used in hanbook and
initial capitalization only applies to proper nouns or starting a
sentence so fix all instances on this page. Some examples of the new
correct usage within a sentence:

 - Scrum *not SCRUM*
 - Scrum master *not Scrum Master*
 - product owner *not Product Owner*
 - sprint *not Sprint*

Also included:
- Fixed full-time team member story point capacity to be 10.
- Fixed links and some small rewording.

### CODE REVIEW

**Comment by zupo** [comment]
Uhm. I'm biased (doh) but I like the current style. When did we decide to change our style? What's the rationale behind it?

**Comment by cas--** [comment]
That is from the Wikipedia style that I am implementing for the handbook.

A project or framework are proper nouns, *user story* is not, it is a description. The use of initial capitalization is adding emphasis where it is usually not required, we have italic, bold and code markup to denote emphasis. Also at what point do we stop adding initial capital letters to processes or labels?

These changes have already been made on several pages and @dmurko queried it but had no strong objection but did point out that I should be consistent so this is the case with this PR to get the work-process pages consistent.

**Comment by marbeann** [comment]
When I first pointed out the inconsistency in the other PR, I did not agree that it should not be capitalized since I’ve always considered it as a proper noun.

When I say ’write a Story’, it’s completely different from ‘write a story’. In the former, it’s asking for a specific thing, while the latter denotes anything.

I read more about it and found that the verdict is still out on the capitalization. Companies write it as how they perceive or use it - nounify (capitalize) or adjectify (not capitalize) it.

Also, everyone needs to made aware of this before we implement any changes.

**Comment by zupo** [comment]
> When I say ’write a Story’, it’s completely different from ‘write a story’. In the former, it’s asking for something specific to us, while the latter denotes a common thing.

This. A hundred times over.

**Comment by cas--** [comment]
> When I say ’write a Story’, it’s completely different from ‘write a story’. In the former, it’s asking for something specific to us, while the latter denotes a common thing.

> This. A hundred times over.

Except that is out of context if it is being used in the user-stories page where it is self-evident what is being referred to and if there is ambiguity then *a/the user story* should be used.

Aside from the reasons I have laid out, there is a precedence set for this, so we I strongly feel we should follow it:

https://developers.google.com/style/capitalization
http://www.mhhe.com/mayfieldpub/tsw/capitals.htm
https://english.stackexchange.com/questions/73930/is-it-proper-to-use-capital-letters-in-e-g-document-names

A document about user story, using lower case: https://www.gov.uk/service-manual/agile-delivery/writing-user-stories
Lower case for the product owner: https://www.mountaingoatsoftware.com/agile/scrum/roles/product-owner

**Comment by cas--** [comment]
Titles of works are different, again Wikipedia style manual covers this in detail https://en.m.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Titles#Capital_letters

**Comment by zupo** [comment]
Yes, but why are O-Ring Seals capitalized? 

In general, adopting Wikipedia writing style is a very sane approach. I just need to wrap my head around how it works.

**Pull request merged**
