### PR TITLE
Reword the github checkbox work process

### PR DESCRIPTION
**Pull request by cas--**
The work process paragraph for checkboxes was too convoluted so updated it.

### CODE REVIEW

**Comment by cas--** [comment]
@marbeann Which version? The original text didn't track well with my other changes and I felt the need to clarify why we use rather than to just nitpick or arbitrarily. How about:

`Note that when you tick a checkbox, in an issue, you should also post a comment. This is so we have a paper trail of the changes to checkboxes since GitHub doesn't do this.`

**Comment by marbeann** [comment]
Let's remove this, please:

>That is it! Go to your onboarding issue and start ticking things off!

It's cheesy and looks out of place in a public handbook.

**Comment by zupo** [comment]
I like cheesy things, but fine, let's remove it.

**Comment by cas--** [comment]
Because of the extra suggested change, I have combined the checkbox sentence back into the original paragraph:

`The onboarding checklist is a GitHub issue created specifically for you. It tracks everything required for a successful onboarding. The list of tasks is ordered by the priority in which you need to tackle them. Also whenever a checkbox in an issue is ticked you should also post a comment. We then have a paper trail of checkbox changes since GitHub doesn't show this.`


Please 'yae' or 'nae' once more :)

**Comment by marbeann** [comment]
👍 .

>Also whenever a checkbox in an issue is ticked you should also post a comment.

I would remove the first _Also_. `Whenever a checkbox in an issue is ticked, you should also post a comment.`

**Pull request merged**
