### PR TITLE
Expand definitions, unify full stops

### PR DESCRIPTION
**Pull request by zupo**

### CODE REVIEW

**Comment by dmurko** [comment]
Umm, why aren't links working?

**Comment by zupo** [comment]
@dmurko: fixed

**Comment by dmurko** [comment]
@zupo I fixed it after you because yours didn't show and I thought it was wrong. It's still wrong though. Your last commit:

screen shot 2017-09-06 at 14 53 15

**Comment by zupo** [comment]
@dmurko: better?

**Comment by dmurko** [comment]
Emm, sure, but it's not a pretty link. Any idea why?

**Comment by zupo** [comment]
I guess Markdown does not support links in definition lists. It's a very basic language.

**Pull request merged**
